### PR TITLE
Added Index, delete, show methods to the booking controller

### PR DESCRIPTION
**Pull request by AishwaryaKanitkar**
- Added the index, delete and show methods in the booking controller
- Added the views for index, delete and show method
- Added links in index for lives

### CODE REVIEW

**Review by kat-s92 — APPROVED** [review]

**Review by kat-s92 — CHANGES_REQUESTED** [review]
@AishwaryaKanitkar could you check your seed file? TY

**Comment by AishwaryaKanitkar** [comment]
Done, checked and updated

**Review by kat-s92 — APPROVED** [review]
lgtm

**Review by kat-s92 — APPROVED** [review]
lgtm

**Pull request merged**
